# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91fdb031fb697fe008a917c28d158e59aaa030843697f84b2f0896ab9bdb10b5d2588045d0b07a413c0691f0ba05804be9c69a823ca3030a915f2965af5dd5ab

test:
  secret_key_base: e9fc1f3103042069605a8bff4fd8dede34831a650e3dbc72b2fe0d2df58b886bd567ad254654de89a86f2d8a145bb9fc383e70649bd1bfc6b8ac43f37def72b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
